WITH customers AS (
  SELECT
    *
  FROM {{ ref('dim_jaffle_customers') }}
), orders AS (
  SELECT
    *
  FROM {{ ref('fct_jaffle_orders') }}
), order_items AS (
  SELECT
    *
  FROM {{ ref('jaffle_order_items') }}
), rename_1 AS (
  SELECT
    *
    RENAME (CUSTOMER_ID AS CUSTOMERS_CUSTOMER_ID)
  FROM customers
), rename_2 AS (
  SELECT
    *
    RENAME (CUSTOMER_ID AS ORDERS_CUSTOMER_ID)
  FROM orders
), aggregate_1 AS (
  SELECT
    ORDER_ID,
    SUM(PRODUCT_PRICE) AS TOTAL_PRODUCT_PRICE,
    SUM(SUPPLY_COST) AS TOTAL_SUPPLY_COST
  FROM order_items
  GROUP BY
    ORDER_ID
), join_1 AS (
  SELECT
    *
  FROM rename_1
  JOIN rename_2
    ON rename_1.CUSTOMERS_CUSTOMER_ID = rename_2.ORDERS_CUSTOMER_ID
), rename_4 AS (
  SELECT
    ORDER_ID AS ORDER_ITEMS_SUMMARY_ORDER_ID,
    TOTAL_PRODUCT_PRICE,
    TOTAL_SUPPLY_COST
  FROM aggregate_1
), rename_3 AS (
  SELECT
    CUSTOMERS_CUSTOMER_ID AS CUSTOMER_ID,
    CUSTOMER_NAME,
    ORDER_ID AS CUSTOMER_ORDERS_ORDER_ID,
    ORDERED_AT,
    ORDER_TOTAL,
    IS_FOOD_ORDER,
    IS_DRINK_ORDER
  FROM join_1
), join_2 AS (
  SELECT
    *
  FROM rename_3
  JOIN rename_4
    ON rename_3.CUSTOMER_ORDERS_ORDER_ID = rename_4.ORDER_ITEMS_SUMMARY_ORDER_ID
), formula_1 AS (
  SELECT
    *,
    CASE WHEN IS_FOOD_ORDER THEN 1 ELSE 0 END AS AGG_FOOD_ORDERS_COUNT_INPUT,
    CASE WHEN IS_DRINK_ORDER THEN 1 ELSE 0 END AS AGG_DRINK_ORDERS_COUNT_INPUT
  FROM join_2
), aggregate_2 AS (
  SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    COUNT(DISTINCT CUSTOMER_ORDERS_ORDER_ID) AS TOTAL_ORDERS,
    MIN(ORDERED_AT) AS FIRST_ORDER_DATE,
    MAX(ORDERED_AT) AS LAST_ORDER_DATE,
    SUM(ORDER_TOTAL) AS TOTAL_SPEND,
    SUM(TOTAL_PRODUCT_PRICE) AS TOTAL_PRODUCT_PRICE,
    SUM(TOTAL_SUPPLY_COST) AS TOTAL_SUPPLY_COST,
    SUM(AGG_FOOD_ORDERS_COUNT_INPUT) AS FOOD_ORDERS_COUNT,
    SUM(AGG_DRINK_ORDERS_COUNT_INPUT) AS DRINK_ORDERS_COUNT
  FROM formula_1
  GROUP BY
    CUSTOMER_ID,
    CUSTOMER_NAME
), order_1 AS (
  SELECT
    *
  FROM aggregate_2
  ORDER BY
    TOTAL_SPEND DESC
  LIMIT 10
), output_1 AS (
  SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    TOTAL_ORDERS,
    FIRST_ORDER_DATE,
    LAST_ORDER_DATE,
    TOTAL_SPEND,
    TOTAL_PRODUCT_PRICE,
    TOTAL_SUPPLY_COST,
    FOOD_ORDERS_COUNT,
    DRINK_ORDERS_COUNT
  FROM order_1
)
SELECT
  *
FROM output_1